const datos = [
{id: 9,cat: 'General Knowledge'},
{id: 10,cat: 'Entertainment: Books'},
{id: 11,cat: 'Entertainment: Film'},
{id: 12,cat: 'Entertainment: Music'},
{id: 13,cat: 'Entertainment: Musicals & Theatres'},
{id: 14,cat: 'Entertainment: Television'},
{id: 15,cat: 'Entertainment: Video Games'},
{id: 16,cat: 'Entertainment: Board Games'},
{id: 17,cat: 'Science & Nature'},
{id: 18,cat: 'Science: Computers'},
{id: 19,cat: 'Science: Mathematics'},
{id: 20,cat: 'Mythology'},
{id: 21,cat: 'Sports'},
{id: 22,cat: 'Geography'},
{id: 23,cat: 'History'},
{id: 24,cat: 'Politics'},
{id: 25,cat: 'Art'},
{id: 26,cat: 'Celebrities'},
{id: 27,cat: 'Animals'},
{id: 28,cat: 'Vehicles'},
{id: 29,cat: 'Entertainment: Comics'},
{id: 30,cat: 'Science: Gadgets'},
{id: 31,cat: 'Entertainment: Japanese Anime & Manga'},
{id: 32,cat: 'Entertainment: Cartoon & Animations'},  
];

