version: "2.1"
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1
workflows:
  test:
    jobs:
      - node/test
      - cypress/run:
          spec: cypress/integration/addtodo_spec.js
